from abc import ABC, abstractmethod
from typing import List

class Storage(ABC):
    @abstractmethod
    def save_members(self, members: List[dict]) -> None: ...
    @abstractmethod
    def load_members(self) -> List[dict]: ...
    @abstractmethod
    def save_events(self, events: List[dict]) -> None: ...
    @abstractmethod
    def load_events(self) -> List[dict]: ...
